### ISSUE TITLE
First release

### ISSUE THREAD

**Issue by wavexx** [wavexx/gtabview#11]
@scls19fr: I'm thinking about a first initial release in pypi. Do you see anything critical missing? Some notes to add to the documentation maybe?

**Comment by scls19fr** [comment]
Yes a pip package will be great.

**Comment by wavexx** [comment]
Package is live. Could you give it a try?

**Comment by scls19fr** [comment]
I've just installed it using:

    $ pip install gtabview

and tested both

- gtabview script
- view function

all is ok

**Comment by wavexx** [comment]
Thanks!

**Comment by scls19fr** [comment]
Thanks too. I will probably use your package with my students for a course about data analysis.

**Comment by wavexx** [comment]
On 24/07/15 18:38, scls19fr wrote:
> Thanks too. I will probably use your package with my students for a
> course about data analysis.

It's a shame the default print layout of pandas, especially on a
terminal, only works for *very* small datasets.

I've seen people using python notebooks *just* for the table display.

And rightly so.. the output of a dataframe in R, for example, is
generally more understandable, and you also have some dumb viewer/editor.

I'm actually quite happy with both tabview/gtabview for this reason.

**Comment by scls19fr** [comment]
Edit function with tabview / gtabview is still missing ;-)
Spider variables editor still have a little advantage.

**Comment by wavexx** [comment]
On 24/07/15 20:24, scls19fr wrote:
> Edit function with tabview / gtabview is still missing ;-)
> Spider variables editor still have a little advantage.

editing existing cells wouldn't be too difficult to do right now.
The qt widget has already most of the functionality built in.

adding removing rows/columns might be tricky when an index/multiindex is
involved though.

does spyder allow the creation of new rows/columns?

**Comment by scls19fr** [comment]
No Spyder variable editor doesn't allow to create new rows/columns in a Numpy Array or a Pandas DataFrame
