### ISSUE TITLE
NumPy matrix view

### ISSUE THREAD

**Issue by scls19fr** [wavexx/gtabview#14]
Hello Yuri,

There is a problem with NumPy arrays

    m = np.matrix([[2,3],[1,2]])
    view(m)

raises

    //anaconda/lib/python3.4/site-packages/gtabview-0.1-py3.4.egg/gtabview/__init__.py:116: RuntimeWarning: cannot visualize the supplied data type: <class 'numpy.matrixlib.defmatrix.matrix'>

Here is a screenshot of Spyder displaying this matrix
![capture d ecran 2015-07-25 a 09 36 10](https://cloud.githubusercontent.com/assets/109167/8888548/cecdcdac-32b1-11e5-83f7-5c5048da7a17.png)

I think you should use duck typing and have a fallback mode to Numpy Arrays and if view function raises an error, display this message.

    In [26]: lst = [[2,3],[1,2]]

    In [27]: a = np.array(lst)

    In [28]: a[0][0]
    Out[28]: 2

    In [29]: a[0, 0]
    Out[29]: 2

    In [30]: m = np.matrix(lst)

    In [31]: m[0][0] # !!!!
    Out[31]: matrix([[2, 3]])

    In [32]: m[0, 0]
    Out[32]: 2

    In [33]: lst[0][0]
    Out[33]: 2

    In [34]: lst[0, 0] # !!!!
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-34-7897f61aa865> in <module>()
    ----> 1 lst[0, 0]

    TypeError: list indices must be integers, not tuple

Kind regards

**Comment by wavexx** [comment]
This, at least, should be fixed now.

**Comment by wavexx** [comment]
I think this deserves a new release.
I also added the ability to transpose the view.

If you could give it a quick test, I'll release 0.2

**Comment by scls19fr** [comment]
If you add tests (see my comments https://github.com/wavexx/gtabview/issues/9) it will be much easier to give it a try (even if tests are not automated)

I noticed a problem with index numbering with lists

![capture d ecran 2015-07-25 a 14 40 26](https://cloud.githubusercontent.com/assets/109167/8889439/1ff03066-32db-11e5-89c7-b48b41effa89.png)

**Comment by wavexx** [comment]
On 25/07/15 14:41, scls19fr wrote:
> I noticed a problem with index numbering with lists

What's the problem with it?

**Comment by scls19fr** [comment]
First row (number 0) is 1 2
row 3 4 should be numbered "1"

**Comment by wavexx** [comment]
On 25/07/15 14:49, scls19fr wrote:
> First row (number 0) is 1 2
> row 3 4 should be numbered "1"

This is because for lists-of-lists (like for files), the first is
assumed to be labels, as there's no way to tell.

idx_rows=0 should do what you want.

**Comment by wavexx** [comment]
On 25/07/15 14:52, Yuri D'Elia wrote:
> On 25/07/15 14:49, scls19fr wrote:
>> First row (number 0) is 1 2
>> row 3 4 should be numbered "1"
> 
> This is because for lists-of-lists (like for files), the first is
> assumed to be labels, as there's no way to tell.
> 
> idx_rows=0 should do what you want.

And by that, I mean hdr_rows.

**Comment by scls19fr** [comment]
Shouldn't we consider that by default there is no header ?

**Comment by wavexx** [comment]
On 25/07/15 14:54, scls19fr wrote:
> Shouldn't we consider that by default there is no header ?

I'm not sure (in either direction).
Sometimes I find it convenient, sometimes not.

**Comment by scls19fr** [comment]
Spyder variables editor display for list is not very nice

![capture d ecran 2015-07-25 a 14 56 21](https://cloud.githubusercontent.com/assets/109167/8889505/54a0f73a-32dd-11e5-90a8-d49997750646.png)

but it is not misleading

because yes... that's quite misleading !

**Comment by wavexx** [comment]
True, especially at the beginning. Should the header be enabled only when loading from a file then?

**Comment by scls19fr** [comment]
Yes I think it's a good idea.

**Comment by wavexx** [comment]
On 25/07/15 15:21, scls19fr wrote:
> Yes I think it's a good idea.

Done.
