### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by scls19fr** [wavexx/gtabview#15]
I want to use [Sourcegraph](https://sourcegraph.com) for gtabview code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/wavexx/gtabview. (It should only take 30 seconds.)

Thank you!

**Comment by scls19fr** [comment]
I should sync Sourcegraph version after every push.

**Comment by wavexx** [comment]
I enabled it. Let me know if it syncs properly (the refresh doesn't seem instantaneous), then close the issue.

**Comment by scls19fr** [comment]
If you connect correctly your project it should build again on next push.

**Comment by scls19fr** [comment]
I'm not sure you connect correctly as I still get

    Only repository admins can view or edit settings.
    Ask the owner to enable this repository.

**Comment by wavexx** [comment]
On 27/07/15 13:04, scls19fr wrote:
> I'm not sure you connect correctly as I still get
> 
> |Only repository admins can view or edit settings. Ask the owner to
> enable this repository. |

It shows me as "connected".
I'll try to push something.

**Comment by scls19fr** [comment]
build is queued

https://sourcegraph.com/github.com/wavexx/gtabview/.builds/2410759

**Comment by wavexx** [comment]
Seems to be working now.
