### ISSUE TITLE
Pandas DataReader is now a stand alone project

### ISSUE THREAD

**Issue by scls19fr** [wavexx/gtabview#3]
Hello,

Pandas DataReader is now a stand alone project.

You might install it

    $ pip install pandas-datareader

And use it using:

    from pandas_datareader import data, wb
    import datetime
    start = datetime.datetime(2010, 1, 1)
    end = datetime.datetime(2013, 1, 27)
    panel = data.DataReader(["F", "YHOO"], 'yahoo', start, end) # Panel
    df = panel.loc[:,:,"F"]

see

http://pandas.pydata.org/pandas-docs/stable/remote_data.html

    Warning In pandas 0.17.0, the sub-package pandas.io.data will be removed in favor of a separately installable pandas-datareader package. This will allow the data modules to be independently updated to your pandas installation. The API for pandas-datareader v0.1.1 is the same as in pandas v0.16.1. (GH8961)
    You should replace the imports of the following:

    from pandas.io import data, wb
    With:

    from pandas_datareader import data, wb

Kind regards

**Comment by wavexx** [comment]
Simplified the example with some dumb values.

**Comment by scls19fr** [comment]
That's a pity because there is no example with panel now.

**Comment by wavexx** [comment]
On 20/07/15 09:46, scls19fr wrote:
> That's a pity because there is no example with panel now.

If you can come up with something that doesn't depend on external data
it would be nice.

Or we could just leave the old example, as it works on old pandas as well.

Despite using pandas reguarly, I have no use for the web reader, and I
will definitely not install it when it's going to be split.
