### ISSUE TITLE
from gtabview import view raises ImportError: cannot import name 'str'

### ISSUE THREAD

**Issue by scls19fr** [wavexx/gtabview#6]
Hello,

after installing gtabview using:

    pc:~ scls$ pip install git+git://github.com/wavexx/gtabview.git
    Collecting git+git://github.com/wavexx/gtabview.git
      Cloning git://github.com/wavexx/gtabview.git to /var/folders/j_/v8b1bst93_94t724ptsswfsr0000gn/T/pip-t_el8_i6-build
    Requirement already satisfied (use --upgrade to upgrade): setuptools in /anaconda/lib/python3.4/site-packages/setuptools-18.0.1-py3.4.egg (from gtabview==0.1)
    Installing collected packages: gtabview
      Running setup.py install for gtabview
    Successfully installed gtabview-0.1

I run IPython and try to import it:

    pc:~ scls$ ipython
    Python 3.4.3 |Anaconda 2.3.0 (x86_64)| (default, Mar  6 2015, 12:07:41)
    Type "copyright", "credits" or "license" for more information.

    IPython 3.2.0 -- An enhanced Interactive Python.
    Anaconda is brought to you by Continuum Analytics.
    Please check out: http://continuum.io/thanks and https://anaconda.org
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.

    In [1]: from gtabview import view
    ---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)
    <ipython-input-1-245551471c0d> in <module>()
    ----> 1 from gtabview import view

    //anaconda/lib/python3.4/site-packages/gtabview/__init__.py in <module>()
         10 import threading
         11
    ---> 12 from .viewer import Viewer, str
         13 from .viewer import QtGui, QtCore
         14

    ImportError: cannot import name 'str'

Sorry.

Kind regards

**Comment by wavexx** [comment]
On 19/07/15 21:52, scls19fr wrote:
> Sorry.

Yeah there are probably a few quirks remaining with python3, since I
never tested it so far. I'll have a run now.

**Comment by scls19fr** [comment]
Anaconda is great for this. You can have easily Python 2 and Python 3.
Python 3 is my default install
I can do

    $ source activate py2

to change to a Python 2 environement

**Comment by wavexx** [comment]
Fixed now.
